### ISSUE TITLE
Weird smudge following the beat cursor on Chrome

### ISSUE THREAD

**Issue by j4kim** [CoderLine/alphaTab#153]
# Your environment

* Version used: (master branch)
* Platform used: JavaScript
* Rendering engine used: SVG
* Browser Name and Version: Chrome 59.0.3071.115 (Build officiel) (64 bits)
* Operating System and version (desktop or mobile): Windows 10

# Observed Results

Video: https://drive.google.com/open?id=0B9wmO5HutHghU2NsNmNZMlltM1k

This occurs only when using a custom scroll element.

# Steps to Reproduce (for bugs)

Same fiddle as the previous issue, but with horizontal mode enabled: https://jsfiddle.net/j4kim/7ho3mmmm/13/

It doesn't happen on every platform. I had my classmates test it and ~half of them sees nothing wrong. The Chrome version doesn't seem to be related...

# Possible Solution 

I don't know if this bug is related to AlphaTab. I still post this issue in case you have an idea and to let you know this is happening on a few users.

**Comment by Danielku15** [comment]
This seems to be known issue for Chrome. They seem to have a bug in CSS animation rendering. I could solve the issue in various ways: 

1) Use RGBA instead of opacity for the barCursor: 
```css
.barCursor {
  /* Defines the color of the bar background when a bar is played */
  background: rgba(255, 242, 0, 0.25);
}
```

2) Add `-webkit-backface-visibility`
```css
.barCursor {
  /* Defines the color of the bar background when a bar is played */
  opacity: 0.25;
  background: #FFF200;
  -webkit-backface-visibility: hidden;
}
```

3) Add a `-webkit-transform:` 
```css
.barCursor {
  /* Defines the color of the bar background when a bar is played */
  opacity: 0.25;
  background: #FFF200;
-webkit-transform: translateZ(0);
}
```

I will update the samples accordingly.
